# Generated by Django 6.0 on 2025-12-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PG_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
